"""add id to comments

Revision ID: 687a4127ce2b
Revises: 326730f8371c
Create Date: 2021-12-21 23:29:10.641398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687a4127ce2b'
down_revision = '326730f8371c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'id')
    # ### end Alembic commands ###
