"""Add content column to Post

Revision ID: 7a036930b60c
Revises: 0443ea739f24
Create Date: 2021-12-20 22:24:22.368520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a036930b60c'
down_revision = '0443ea739f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###
